apiVersion: apps/v1
kind: Deployment
metadata:
  name: explore-mfg-demo
  namespace: explore-mfg-demo
spec:
  template:
    spec:
      containers:
      - name: explore-mfg-demo
        env:
        - name: DEVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: explore-mfg-demo-map
              key: DEVICE_NAME
        - name: VIDEO_URL
          valueFrom:
            configMapKeyRef:
              name: explore-mfg-demo-map
              key: VIDEO_URL
        - name: NODE_RED_DATA_URL
          valueFrom:
            configMapKeyRef:
              name: explore-mfg-demo-map
              key: NODE_RED_DATA_URL
        - name: VERTICAL_LINES
          valueFrom:
            configMapKeyRef:
              name: explore-mfg-demo-map
              key: VERTICAL_LINES
        - name: HORIZONTAL_LINES
          valueFrom:
            configMapKeyRef:
              name: explore-mfg-demo-map
              key: HORIZONTAL_LINES